import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { type ExecutionPlan } from '../core/execution/execution-plan.js';

export interface ArtifactGeneratorOptions {
  artifactRoot?: string;
}

export class ArtifactGenerator {
  private readonly artifactRoot: string;

  public constructor(options: ArtifactGeneratorOptions = {}) {
    this.artifactRoot = resolve(options.artifactRoot ?? 'artifacts');
  }

  public generateWebPlaywrightSource(plan: ExecutionPlan): string {
    const lines = [
      "import { test, expect } from '@playwright/test';",
      '',
      `test(${JSON.stringify(plan.intent.description)}, async ({ page }) => {`,
    ];
    for (const step of plan.steps) {
      const target = step.target;
      switch (step.action) {
        case 'navigate':
          lines.push(`  await page.goto(${JSON.stringify(target.url ?? '')});`);
          break;
        case 'click':
          lines.push(`  await ${this.locator(target)}.click();`);
          break;
        case 'fill':
          lines.push(`  await ${this.locator(target)}.fill(${JSON.stringify(step.value ?? '')});`);
          break;
        case 'select':
          lines.push(
            `  await ${this.locator(target)}.selectOption(${JSON.stringify(step.value ?? '')});`,
          );
          break;
        case 'wait':
          lines.push(`  await page.waitForTimeout(${Number(step.value ?? 0)});`);
          break;
        case 'assert':
          if (step.expected?.url)
            lines.push(`  await expect(page).toHaveURL(${JSON.stringify(step.expected.url)});`);
          else if (step.expected?.text)
            lines.push(
              `  await expect(${this.locator(target)}).toContainText(${JSON.stringify(step.expected.text)});`,
            );
          else if (step.expected?.visible)
            lines.push(`  await expect(${this.locator(target)}).toBeVisible();`);
          else lines.push(`  // Assertion ${step.id} is represented by the normalized intent.`);
          break;
        case 'extract':
          lines.push(`  const extracted_${safeIdentifier(step.id)} = await ${this.locator(target)}.allTextContents();`);
          break;
        case 'request':
          lines.push(`  // API step ${step.id} is not generated by the Web artifact generator.`);
          break;
      }
    }
    lines.push('});', '');
    return lines.join('\n');
  }

  public async generateWebPlaywrightArtifact(plan: ExecutionPlan): Promise<string | undefined> {
    if (plan.domain !== 'web') return undefined;
    const directory = resolve(
      this.artifactRoot,
      'executions',
      safeId(plan.executionId),
      'generated',
    );
    await mkdir(directory, { recursive: true });
    const path = resolve(directory, 'playwright-test.spec.ts');
    await writeFile(path, this.generateWebPlaywrightSource(plan));
    return path;
  }

  private locator(target: ExecutionPlan['steps'][number]['target']): string {
    if (target.semanticLabel && target.role)
      return `page.getByRole(${JSON.stringify(target.role)}, { name: ${JSON.stringify(target.semanticLabel)} })`;
    if (target.semanticLabel) return `page.getByLabel(${JSON.stringify(target.semanticLabel)})`;
    if (target.role) return `page.getByRole(${JSON.stringify(target.role)})`;
    if (target.placeholder) return `page.getByPlaceholder(${JSON.stringify(target.placeholder)})`;
    if (target.text) return `page.getByText(${JSON.stringify(target.text)})`;
    return "page.locator('body')";
  }
}

function safeIdentifier(value: string): string {
  const identifier = value.replace(/[^a-zA-Z0-9_$]/g, '_');
  return /^[a-zA-Z_$]/.test(identifier) ? identifier : `step_${identifier}`;
}

function safeId(value: string): string {
  return value.replace(/[^a-zA-Z0-9_-]/g, '_');
}
